export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { ThemeProvider } from "../components/ui/ThemeProvider";
import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
